name: Build and Release musicplayer (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      QT_VERSION: '5.15.2'
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install taglib:x64-windows
          .\vcpkg\vcpkg install ffmpeg:x64-windows

      - name: Configure CMake
        run: |
          $vcpkgDir = "$pwd/vcpkg"
          $toolchainFile = "$vcpkgDir/scripts/buildsystems/vcpkg.cmake"
          Write-Host "Using toolchain file: $toolchainFile"
          if (Test-Path $toolchainFile) {
            Write-Host "Toolchain file exists"
          } else {
            Write-Host "Toolchain file does not exist"
            Get-ChildItem -Path $vcpkgDir -Recurse -Name | Where-Object { $_ -like "*vcpkg.cmake" }
            exit 1
          }
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$toolchainFile"

      - name: Build
        run: cmake --build build --config Release

      - name: Copy dependencies
        run: |
          copy build\Release\musicplayer.exe .
          copy .\vcpkg\installed\x64-windows\bin\tag.dll .
          copy .\vcpkg\installed\x64-windows\bin\avcodec-*.dll .
          copy .\vcpkg\installed\x64-windows\bin\avformat-*.dll .
          copy .\vcpkg\installed\x64-windows\bin\avutil-*.dll .
          copy .\vcpkg\installed\x64-windows\bin\swresample-*.dll .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            musicplayer.exe
            tag.dll
            avcodec-*.dll
            avformat-*.dll
            avutil-*.dll
            swresample-*.dll
            resources/icon.png
        env:
          GITHUB_TOKEN: ${{ secrets.A }}
