name: Build and Release musicplayer (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      QT_VERSION: '5.15.2'
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Install Chocolatey (for pkg-config)
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install pkg-config
        run: choco install pkgconfiglite

      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install taglib:x64-windows
          .\vcpkg\vcpkg install ffmpeg:x64-windows

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release

      - name: Copy dependencies (FFmpeg/TagLib DLL)
        run: |
          copy build\Release\musicplayer.exe .
          REM Copy DLL from vcpkg installed bin directory as needed
          REM Example:
          REM copy .\vcpkg\installed\x64-windows\bin\*.dll .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            musicplayer.exe
            *.dll
            resources/icon.png
        env:
          GITHUB_TOKEN: ${{ secrets.A}}
