name: Build and Release musicplayer (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      QT_VERSION: '5.15.2'
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install taglib:x64-windows
          .\vcpkg\vcpkg install ffmpeg:x64-windows
          .\vcpkg\vcpkg install pkgconf:x64-windows

      - name: Check and fix source file encoding
        run: |
          # 检查并修复源文件中的非法字符
          $files = Get-ChildItem -Recurse -Include *.h, *.cpp -File
          foreach ($file in $files) {
            $content = Get-Content -Path $file.FullName -Raw
            # 移除非法字符（如中文标点符号）
            $cleanContent = $content -replace '[^\x00-\x7F]', ''
            if ($content -ne $cleanContent) {
              Write-Host "Cleaning invalid characters in $($file.FullName)"
              Set-Content -Path $file.FullName -Value $cleanContent -NoNewline
            }
          }

      - name: Configure CMake
        run: |
          $vcpkgPath = "${{ github.workspace }}/vcpkg"
          $toolchainFile = "$vcpkgPath/scripts/buildsystems/vcpkg.cmake"
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$toolchainFile -DCMAKE_PREFIX_PATH="$vcpkgPath/installed/x64-windows" -DCMAKE_CXX_FLAGS="/utf-8"

      - name: Build
        run: cmake --build build --config Release

      - name: Copy dependencies
        run: |
          copy build\Release\musicplayer.exe .
          copy .\vcpkg\installed\x64-windows\bin\tag.dll .
          copy .\vcpkg\installed\x64-windows\bin\avcodec-*.dll .
          copy .\vcpkg\installed\x64-windows\bin\avformat-*.dll .
          copy .\vcpkg\installed\x64-windows\bin\avutil-*.dll .
          copy .\vcpkg\installed\x64-windows\bin\swresample-*.dll .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            musicplayer.exe
            tag.dll
            avcodec-*.dll
            avformat-*.dll
            avutil-*.dll
            swresample-*.dll
            resources/icon.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
