name: Build and Release musicplayer (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      QT_VERSION: '5.15.2'
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install taglib:x64-windows
          .\vcpkg\vcpkg install ffmpeg:x64-windows
          .\vcpkg\vcpkg install pkgconf:x64-windows

      - name: Clean source files from invalid characters
        run: |
          # 清理所有源文件中的非法字符
          $files = Get-ChildItem -Recurse -Include *.h, *.cpp -File
          foreach ($file in $files) {
              $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
              # 移除所有非ASCII字符
              $cleanContent = $content -replace '[^\x00-\x7F]', ''
              if ($content -ne $cleanContent) {
                  Write-Host "Cleaning invalid characters in $($file.FullName)"
                  Set-Content -Path $file.FullName -Value $cleanContent -NoNewline -Encoding UTF8
              }
          }

      - name: Configure CMake
        run: |
          $vcpkgDir = "$pwd/vcpkg"
          $toolchainFile = "$vcpkgDir/scripts/buildsystems/vcpkg.cmake"
          Write-Host "Using toolchain file: $toolchainFile"
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$toolchainFile" -DCMAKE_PREFIX_PATH="$vcpkgDir/installed/x
